/**
 * This file was automatically generated by simpleapp generator. Every
 * MODIFICATION OVERRIDE BY GENERATEOR
 * last change 2025-06-18
 * Author: --
 */

import { MINI_APP_BRIDGE_MESSAGES } from "../constants/common.constant";
import {
  MiniAppBridgeMessageApi,
  MiniAppBridgeMessageApiResponse,
  MiniAppBridgeMessageAuthToken,
  MiniAppBridgeMessageAuthTokenResponse,
  MiniAppBridgeMessageOpenOnScreenResourceForm,
} from "../types/bridge.type";
import {
  MiniAppResourceServiceApiParam,
  MiniAppResourceServiceOpenOnScreenResourceFormParam,
} from "../types/service.type";

export class MiniAppBridgeService {
  private pendingRequests: Record<
    string,
    { resolve: (data: any) => void; reject: (err: any) => void }
  > = {};

  constructor() {
    if (typeof window !== "undefined") {
      window.addEventListener("message", event => {
        const message:
          | MiniAppBridgeMessageApiResponse<any>
          | MiniAppBridgeMessageAuthTokenResponse = event.data;

        const isApiResponse =
          message.type === MINI_APP_BRIDGE_MESSAGES.API_RESPONSE;
        const isAuthResponse =
          message.type === MINI_APP_BRIDGE_MESSAGES.AUTH_TOKEN_RESPONSE;
        if ((!isApiResponse && !isAuthResponse) || !message.requestId) return;

        const handler = this.pendingRequests[message.requestId];
        if (!handler) return;

        if (message.success) {
          handler.resolve(
            isAuthResponse
              ? (message as MiniAppBridgeMessageAuthTokenResponse).token
              : (message as MiniAppBridgeMessageApiResponse<any>).data,
          );
        } else {
          handler.reject(message.error);
        }
        delete this.pendingRequests[message.requestId];
      });
    }
  }

  async callApi<TResponse>(
    resource: string,
    action: string,
    params: MiniAppResourceServiceApiParam = {}
  ) {
    const requestId = crypto.randomUUID();

    // TODO: Type
    const requestMessage: MiniAppBridgeMessageApi<any> = {
      type: MINI_APP_BRIDGE_MESSAGES.API,
      requestId,
      params: {
        resource: { name: resource, id: params.id },
        action,
        query: params.query,
        body: params.body,
        queryParams: params.queryParams,
      },
    };

    const promise = new Promise<TResponse>((resolve, reject) => {
      this.pendingRequests[requestId] = { resolve, reject };
    });

    window.parent.postMessage(requestMessage, "*");
    return promise;
  }

  async getAuthToken(): Promise<string> {
    const requestId = crypto.randomUUID();

    const requestMessage: MiniAppBridgeMessageAuthToken = {
      type: MINI_APP_BRIDGE_MESSAGES.AUTH_TOKEN,
      requestId,
    };

    const promise = new Promise<string>((resolve, reject) => {
      this.pendingRequests[requestId] = { resolve, reject };
    });

    window.parent.postMessage(requestMessage, "*");
    return promise;
  }

  openOnScreenResourceForm(
    resource: string,
    params: MiniAppResourceServiceOpenOnScreenResourceFormParam = {}
  ) {
    const message: MiniAppBridgeMessageOpenOnScreenResourceForm = {
      type: MINI_APP_BRIDGE_MESSAGES.OPEN_ON_SCREEN_RESOURCE_FORM,
      params: {
        resource: { name: resource, id: params.id },
        data: params.data,
      },
    };

    window.parent.postMessage(message, "*");
  }
}
