/* tslint:disable */
/* eslint-disable */
/**
 * simtrain-eco backend api
 * Internal use only (generator: 2.0.0w-alpha)
 *
 * The version of the OpenAPI document: 2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export * from "./api";
export * from "./configuration";
