/**
 * This file was automatically generated by simpleapp generator. Every
 * MODIFICATION OVERRIDE BY GENERATEOR
 * last change 2025-06-18
 * Author: --
 */

export enum MINI_APP_BRIDGE_MESSAGES {
  NAVIGATE = "NAVIGATE",
  OPEN_ON_SCREEN_RESOURCE_FORM = "OPEN_ON_SCREEN_RESOURCE_FORM",
  API = "API",
  API_RESPONSE = "API_RESPONSE",
}
