/**
 * This file was automatically generated by simpleapp generator. Every
 * MODIFICATION OVERRIDE BY GENERATEOR
 * last change 2025-06-18
 * Author: --
 */

import { MINI_APP_BRIDGE_MESSAGES } from "../constants/common.constant";

export type MiniAppResource = {
  name: string;
  id?: string;
};

/************************************* Bridge Message Type *************************************/

export type MiniAppBridgeMessage<TAction> =
  | MiniAppBridgeMessageNavigate
  | MiniAppBridgeMessageNavigateCurrentMiniApp
  | MiniAppBridgeMessageOpenOnScreenResourceForm
  | MiniAppBridgeMessageApi<TAction>
  | MiniAppBridgeMessageInitResponse;

export type MiniAppBridgeMessageNavigate = {
  type: typeof MINI_APP_BRIDGE_MESSAGES.NAVIGATE;
  params: {
    target: string;
    id?: string;
    query?: string;
  };
};

export type MiniAppBridgeMessageNavigateCurrentMiniApp = {
  type: typeof MINI_APP_BRIDGE_MESSAGES.NAVIGATE_CURRENT_MINI_APP;
  params: {
    target: string;
    query?: string;
  };
};

export type MiniAppBridgeMessageOpenOnScreenResourceForm = {
  type: typeof MINI_APP_BRIDGE_MESSAGES.OPEN_ON_SCREEN_RESOURCE_FORM;
  params: {
    resource: MiniAppResource;
    data?: any;
  };
};

export type MiniAppBridgeMessageApi<TActions> = {
  type: typeof MINI_APP_BRIDGE_MESSAGES.API;
  requestId: string;
  params: {
    action: TActions;
    resource: MiniAppResource;
    /**
     * For auto complete filter
     */
    query?: string;
    /**
     * For :id/:code/xxx
     */
    queryParams?: {
      [key: string]: any;
    };
    body?: {
      [key: string]: any;
    };
  };
};

export type MiniAppBridgeMessageApiResponse<TData> = {
  type: typeof MINI_APP_BRIDGE_MESSAGES.API_RESPONSE;
  requestId: string;
  success: boolean;
  data?: TData;
  error?: any;
};

export type MiniAppBridgeMessageInitResponse = {
  type: typeof MINI_APP_BRIDGE_MESSAGES.INIT_RESPONSE;
};
