/**
 * This file was automatically generated by simpleapp generator. Every
 * MODIFICATION OVERRIDE BY GENERATEOR
 * last change 2025-06-18
 * Author: --
 */

export type MiniAppResourceServiceApiParam = {
  id?: string;
  queryParams?: {
    [key: string]: any;
  };
  query?: string;
  // TODO: Type
  body?: any;
};

export type MiniAppOnScreenResourceFormCallback = (
  eventType: "create" | "update" | "delete",
  data: any,
  visible: boolean
) => Promise<void>;

export type MiniAppResourceServiceOpenOnScreenResourceFormParam = {
  id?: string;
  // TODO: Type
  data?: any;

  callback?: MiniAppOnScreenResourceFormCallback;
};
