/**
 * This file was automatically generated by simpleapp generator. Every
 * MODIFICATION OVERRIDE BY GENERATEOR
 * last change 2025-06-18
 * Author: --
 */

export type MiniAppResourceServiceApiParam = {
  id?: string;
  queryParams?: {
    [key: string]: any;
  };
  query?: string;
  // TODO: Type
  body?: any;
};

export type MiniAppResourceServiceOpenOnScreenResourceFormParam = {
  id?: string;
  // TODO: Type
  data?: any;
};
