/**
 * This file was automatically generated by simpleapp generator. Every
 * MODIFICATION OVERRIDE BY GENERATEOR
 * last change 2025-06-18
 * Author: --
 */

import { MiniAppBridgeService } from "../bridge.service";

export class MiniAppDocumentEventBridgeService {
  private bridge: MiniAppBridgeService;

  private resourceName = "documentEvent";

  constructor(bridge: MiniAppBridgeService) {
    this.bridge = bridge;
  }

  openOnScreenForm(id?: string) {
    this.bridge.openOnScreenResourceForm(this.resourceName, {
      id,
    });
  }
}
