/**
 * This file was automatically generated by simpleapp generator. Every
 * MODIFICATION OVERRIDE BY GENERATEOR
 * last change 2025-06-18
 * Author: --
 */

import { MiniAppApiListParam } from "../../types/bridge.type";
import { MiniAppBridgeService } from "../bridge.service";
import * as Schema from "../../openapi/backend-api";
import {
  CreateResource,
  PatchResource,
  UpdateResource,
} from "../../types/common";
import { MiniAppOnScreenResourceFormCallback } from "../../types/service.type";

export class MiniAppInvoiceBridgeService {
  private bridge: MiniAppBridgeService;

  private resourceName = "invoice";

  constructor(bridge: MiniAppBridgeService) {
    this.bridge = bridge;
  }

  async list(params?: MiniAppApiListParam | undefined) {
    return this.bridge.callApi<Schema.Invoice[]>(this.resourceName, "list", {
      body: params,
    });
  }

  async detail(id: string) {
    return this.bridge.callApi<Schema.Invoice>(this.resourceName, "detail", {
      id,
    });
  }

  async autoComplete(query: string, data: any) {
    return this.bridge.callApi<Schema.InvoiceAutoComplete[]>(
      this.resourceName,
      "autoComplete",
      {
        query,
        body: data,
      }
    );
  }

  async create(data: CreateResource<Schema.Invoice>) {
    return this.bridge.callApi<Schema.Invoice>(this.resourceName, "create", {
      body: data,
    });
  }

  async patch(id: string, data: PatchResource<Schema.Invoice>) {
    return this.bridge.callApi<Schema.Invoice>(this.resourceName, "patch", {
      id,
      body: data,
    });
  }

  async print(id: string, formatId: string) {
    return this.bridge.callApi<string>(this.resourceName, "print", {
      id: id,
      queryParams: {
        formatId: formatId,
      },
    });
  }

  openOnScreenForm(
    id?: string,
    callback?: MiniAppOnScreenResourceFormCallback
  ) {
    this.bridge.openOnScreenResourceForm(this.resourceName, {
      id,
      callback,
    });
  }
}
