/**
 * This file was automatically generated by simpleapp generator. Every
 * MODIFICATION OVERRIDE BY GENERATEOR
 * last change 2025-06-18
 * Author: --
 */

import { MiniAppApiListParam } from "../../types/bridge.type";
import { MiniAppBridgeService } from "../bridge.service";
import * as Schema from "../../openapi/backend-api";
import {
  CreateResource,
  PatchResource,
  UpdateResource,
} from "../../types/common";

export class MiniAppLevelBridgeService {
  private bridge: MiniAppBridgeService;

  private resourceName = "level";

  constructor(bridge: MiniAppBridgeService) {
    this.bridge = bridge;
  }

  async list(params?: MiniAppApiListParam | undefined) {
    return this.bridge.callApi<Schema.Level[]>(this.resourceName, "list", {
      body: params,
    });
  }

  async detail(id: string) {
    return this.bridge.callApi<Schema.Level>(this.resourceName, "detail", {
      id,
    });
  }

  async autoComplete(query: string, data: any) {
    return this.bridge.callApi<Schema.LevelAutoComplete[]>(
      this.resourceName,
      "autoComplete",
      {
        query,
        body: data,
      }
    );
  }

  async searchWithRelation(data: Schema.SearchLevelWithRelations) {
    return this.bridge.callApi<Schema.LevelWithRelation[]>(
      this.resourceName,
      "searchWithRelation",
      {
        body: data,
      }
    );
  }

  openOnScreenForm(id?: string) {
    this.bridge.openOnScreenResourceForm(this.resourceName, {
      id,
    });
  }
}
