/**
 * This file was automatically generated by simpleapp generator. Every
 * MODIFICATION OVERRIDE BY GENERATEOR
 * last change 2025-06-18
 * Author: --
 */

import { MiniAppBridgeService } from "../bridge.service";

export class MiniAppLevelBridgeService {
  private bridge: MiniAppBridgeService;

  private resourceName = "level";

  constructor(bridge: MiniAppBridgeService) {
    this.bridge = bridge;
  }

  async list() {
    return this.bridge.callApi(this.resourceName, "list");
  }

  async detail(id: string) {
    return this.bridge.callApi(this.resourceName, "detail", { id });
  }

  async autoComplete(query: string, data: any) {
    return this.bridge.callApi(this.resourceName, "autoComplete", {
      query,
      body: data,
    });
  }

  openOnScreenForm(id?: string) {
    this.bridge.openOnScreenResourceForm(this.resourceName, {
      id,
    });
  }
}
