/**
 * This file was automatically generated by simpleapp generator. Every
 * MODIFICATION OVERRIDE BY GENERATEOR
 * last change 2025-06-18
 * Author: --
 */

import { MiniAppApiListParam } from "../../types/bridge.type";
import { MiniAppBridgeService } from "../bridge.service";

export class MiniAppOrganizationBridgeService {
  private bridge: MiniAppBridgeService;

  private resourceName = "organization";

  constructor(bridge: MiniAppBridgeService) {
    this.bridge = bridge;
  }

  async current() {
    return this.bridge.callApi(this.resourceName, "current");
  }

  async list(params: MiniAppApiListParam | undefined) {
    return this.bridge.callApi(this.resourceName, "list", { body: params });
  }

  async detail(id: string) {
    return this.bridge.callApi(this.resourceName, "detail", { id });
  }

  async autoComplete(query: string, data: any) {
    return this.bridge.callApi(this.resourceName, "autoComplete", {
      query,
      body: data,
    });
  }

  openOnScreenForm(id?: string) {
    this.bridge.openOnScreenResourceForm(this.resourceName, {
      id,
    });
  }
}
