/**
 * This file was automatically generated by simpleapp generator. Every
 * MODIFICATION OVERRIDE BY GENERATEOR
 * last change 2025-06-18
 * Author: --
 */

import { MiniAppBridgeService } from "../bridge.service";

export class MiniAppPluginInstallationBridgeService {
  private bridge: MiniAppBridgeService;

  private resourceName = "pluginInstallation";

  constructor(bridge: MiniAppBridgeService) {
    this.bridge = bridge;
  }

  async current() {
    return this.bridge.callApi(this.resourceName, "current");
  }

  async detail(id: string) {
    return this.bridge.callApi(this.resourceName, "detail", { id });
  }

  openOnScreenForm(id?: string) {
    this.bridge.openOnScreenResourceForm(this.resourceName, {
      id,
    });
  }
}
