/**
 * This file was automatically generated by simpleapp generator. Every
 * MODIFICATION OVERRIDE BY GENERATEOR
 * last change 2025-06-18
 * Author: --
 */

import { MiniAppApiListParam } from "../../types/bridge.type";
import { MiniAppBridgeService } from "../bridge.service";
import * as Schema from "../../openapi/backend-api";
import {
  CreateResource,
  PatchResource,
  UpdateResource,
} from "../../types/common";

export class MiniAppScheduleAttendanceBridgeService {
  private bridge: MiniAppBridgeService;

  private resourceName = "scheduleAttendance";

  constructor(bridge: MiniAppBridgeService) {
    this.bridge = bridge;
  }

  async create(data: CreateResource<Schema.ScheduleAttendance>) {
    return this.bridge.callApi<Schema.ScheduleAttendance>(
      this.resourceName,
      "create",
      { body: data }
    );
  }

  async update(id: string, data: UpdateResource<Schema.ScheduleAttendance>) {
    return this.bridge.callApi<Schema.ScheduleAttendance>(
      this.resourceName,
      "update",
      { id, body: data }
    );
  }

  openOnScreenForm(id?: string) {
    this.bridge.openOnScreenResourceForm(this.resourceName, {
      id,
    });
  }
}
