/**
 * This file was automatically generated by simpleapp generator. Every
 * MODIFICATION OVERRIDE BY GENERATEOR
 * last change 2025-06-18
 * Author: --
 */

import { MiniAppApiListParam } from "../../types/bridge.type";
import { MiniAppBridgeService } from "../bridge.service";

export class MiniAppScheduleAttendanceBridgeService {
  private bridge: MiniAppBridgeService;

  private resourceName = "scheduleAttendance";

  constructor(bridge: MiniAppBridgeService) {
    this.bridge = bridge;
  }

  async create(data: any) {
    return this.bridge.callApi(this.resourceName, "create", { body: data });
  }

  async update(id: string, data: any) {
    return this.bridge.callApi(this.resourceName, "update", { id, body: data });
  }

  openOnScreenForm(id?: string) {
    this.bridge.openOnScreenResourceForm(this.resourceName, {
      id,
    });
  }
}
