/**
 * This file was automatically generated by simpleapp generator. Every
 * MODIFICATION OVERRIDE BY GENERATEOR
 * last change 2025-06-18
 * Author: --
 */

import { MiniAppApiListParam } from "../../types/bridge.type";
import { MiniAppBridgeService } from "../bridge.service";
import * as Schema from "../../openapi/backend-api";
import {
  CreateResource,
  PatchResource,
  UpdateResource,
} from "../../types/common";

export class MiniAppStudentBridgeService {
  private bridge: MiniAppBridgeService;

  private resourceName = "student";

  constructor(bridge: MiniAppBridgeService) {
    this.bridge = bridge;
  }

  async list(params?: MiniAppApiListParam | undefined) {
    return this.bridge.callApi<Schema.Student[]>(this.resourceName, "list", {
      body: params,
    });
  }

  async detail(id: string) {
    return this.bridge.callApi<Schema.Student>(this.resourceName, "detail", {
      id,
    });
  }

  async create(data: CreateResource<Schema.Student>) {
    return this.bridge.callApi<Schema.Student>(this.resourceName, "create", {
      body: data,
    });
  }

  async update(id: string, data: UpdateResource<Schema.Student>) {
    return this.bridge.callApi<Schema.Student>(this.resourceName, "update", {
      id,
      body: data,
    });
  }

  async patch(id: string, data: PatchResource<Schema.Student>) {
    return this.bridge.callApi<Schema.Student>(this.resourceName, "patch", {
      id,
      body: data,
    });
  }

  async delete(id: string) {
    return this.bridge.callApi(this.resourceName, "delete", { id });
  }

  async autoComplete(query: string, data: any) {
    return this.bridge.callApi<Schema.StudentAutoComplete[]>(
      this.resourceName,
      "autoComplete",
      {
        query,
        body: data,
      }
    );
  }

  async getStudentSummary(id: string) {
    return this.bridge.callApi<Schema.StudentWithSummary>(
      this.resourceName,
      "getStudentSummary",
      {
        id: id,
      }
    );
  }

  async getPhoto(id: string) {
    return this.bridge.callApi<string>(this.resourceName, "getPhoto", {
      id: id,
    });
  }

  async uploadPhoto(id: string, data: Schema.UploadPhoto) {
    return this.bridge.callApi<string>(this.resourceName, "uploadPhoto", {
      id: id,
      body: data,
    });
  }

  openOnScreenForm(id?: string) {
    this.bridge.openOnScreenResourceForm(this.resourceName, {
      id,
    });
  }
}
