/**
 * This file was automatically generated by simpleapp generator. Every
 * MODIFICATION OVERRIDE BY GENERATEOR
 * last change 2025-06-18
 * Author: --
 */

import { MiniAppApiListParam } from "../../types/bridge.type";
import { MiniAppBridgeService } from "../bridge.service";
import * as Schema from "../../openapi/backend-api";
import {
  CreateResource,
  PatchResource,
  UpdateResource,
} from "../../types/common";

export class MiniAppTeacherBridgeService {
  private bridge: MiniAppBridgeService;

  private resourceName = "teacher";

  constructor(bridge: MiniAppBridgeService) {
    this.bridge = bridge;
  }

  async list(params?: MiniAppApiListParam | undefined) {
    return this.bridge.callApi<Schema.Teacher[]>(this.resourceName, "list", {
      body: params,
    });
  }

  async detail(id: string) {
    return this.bridge.callApi<Schema.Teacher>(this.resourceName, "detail", {
      id,
    });
  }

  async create(data: CreateResource<Schema.Teacher>) {
    return this.bridge.callApi<Schema.Teacher>(this.resourceName, "create", {
      body: data,
    });
  }

  async update(id: string, data: UpdateResource<Schema.Teacher>) {
    return this.bridge.callApi<Schema.Teacher>(this.resourceName, "update", {
      id,
      body: data,
    });
  }

  async patch(id: string, data: PatchResource<Schema.Teacher>) {
    return this.bridge.callApi<Schema.Teacher>(this.resourceName, "patch", {
      id,
      body: data,
    });
  }

  async delete(id: string) {
    return this.bridge.callApi(this.resourceName, "delete", { id });
  }

  async autoComplete(query: string, data: any) {
    return this.bridge.callApi<Schema.TeacherAutoComplete[]>(
      this.resourceName,
      "autoComplete",
      {
        query,
        body: data,
      }
    );
  }

  async getTeacherCommissionResult(period: string) {
    return this.bridge.callApi<Schema.CommissionResponseData[]>(
      this.resourceName,
      "getTeacherCommissionResult",
      {
        queryParams: {
          period: period,
        },
      }
    );
  }

  async getPhoto(id: string) {
    return this.bridge.callApi<string>(this.resourceName, "getPhoto", {
      id: id,
    });
  }

  async uploadPhoto(id: string, data: Schema.UploadPhoto) {
    return this.bridge.callApi<string>(this.resourceName, "uploadPhoto", {
      id: id,
      body: data,
    });
  }

  openOnScreenForm(id?: string) {
    this.bridge.openOnScreenResourceForm(this.resourceName, {
      id,
    });
  }
}
