/**
 * This file was automatically generated by simpleapp generator. Every
 * MODIFICATION OVERRIDE BY GENERATEOR
 * last change 2025-06-18
 * Author: --
 */

import { MiniAppApiListParam } from "../../types/bridge.type";
import { MiniAppBridgeService } from "../bridge.service";
import * as Schema from "../../openapi/backend-api";
import {
  CreateResource,
  PatchResource,
  UpdateResource,
} from "../../types/common";

export class MiniAppUserBridgeService {
  private bridge: MiniAppBridgeService;

  private resourceName = "user";

  constructor(bridge: MiniAppBridgeService) {
    this.bridge = bridge;
  }

  async current() {
    return this.bridge.callApi(this.resourceName, "current");
  }

  async list(params?: MiniAppApiListParam | undefined) {
    return this.bridge.callApi<Schema.User[]>(this.resourceName, "list", {
      body: params,
    });
  }

  async detail(id: string) {
    return this.bridge.callApi<Schema.User>(this.resourceName, "detail", {
      id,
    });
  }

  async autoComplete(query: string, data: any) {
    return this.bridge.callApi<Schema.UserAutoComplete[]>(
      this.resourceName,
      "autoComplete",
      {
        query,
        body: data,
      }
    );
  }

  async getPhoto(id: string) {
    return this.bridge.callApi<string>(this.resourceName, "getPhoto", {
      id: id,
    });
  }

  async uploadPhoto(id: string, data: Schema.UploadPhoto) {
    return this.bridge.callApi<string>(this.resourceName, "uploadPhoto", {
      id: id,
      body: data,
    });
  }

  openOnScreenForm(id?: string) {
    this.bridge.openOnScreenResourceForm(this.resourceName, {
      id,
    });
  }
}
