/**
 * This file was automatically generated by simpleapp generator. Every
 * MODIFICATION OVERRIDE BY GENERATEOR
 * last change 2025-06-18
 * Author: --
 */

import { MINI_APP_BRIDGE_MESSAGES } from "./constants/common.constant";
import { MiniAppBridgeResourceAccessor } from "./services/bridge-resource-accessor.service";
import {
  MiniAppBridgeMessageNavigate,
  MiniAppBridgeMessageNavigateCurrentMiniApp,
} from "./types/bridge.type";
import { NavigateToOptions } from "./types/navigate.type";

export class SimtrainEcoMiniAppJsSdk extends MiniAppBridgeResourceAccessor {
  public ui = {
    navigateTo: (
      target: string,
      id?: string,
      query?: string,
      options?: NavigateToOptions
    ) => {
      const message: MiniAppBridgeMessageNavigate = {
        type: MINI_APP_BRIDGE_MESSAGES.NAVIGATE,
        params: { target, id, query, options },
      };

      window.parent.postMessage(message, "*");
    },
  };

  public current = {
    navigateTo: (
      target: string,
      query?: string,
      options?: NavigateToOptions
    ) => {
      const message: MiniAppBridgeMessageNavigateCurrentMiniApp = {
        type: MINI_APP_BRIDGE_MESSAGES.NAVIGATE_CURRENT_MINI_APP,
        params: { target, query, options },
      };

      window.parent.postMessage(message, "*");
    },
  };

  constructor() {
    super();
    // console.log("Hello from SimtrainEcoMiniAppJsSdk !!!");
  }
}
