/**
 * This file was automatically generated by simpleapp generator. Every
 * MODIFICATION OVERRIDE BY GENERATEOR
 * last change 2025-06-18
 * Author: --
 */

import { MINI_APP_BRIDGE_MESSAGES } from './constants/common.constant';
import { MiniAppBridgeResourceAccessor } from './services/bridge-resource-accessor.service';
import { MiniAppBridgeMessageNavigate } from './types/bridge.type';

export class SimtrainEcoMiniAppJsSdk extends MiniAppBridgeResourceAccessor {
  public ui = {
    navigateTo: (target: string, id?: string, query?: string) => {
      const message: MiniAppBridgeMessageNavigate = {
        type: MINI_APP_BRIDGE_MESSAGES.NAVIGATE,
        params: { target, id, query }
      };

      window.parent.postMessage(message, '*');
    }
  };

  constructor() {
    super();
    console.log('Hello from SimtrainEcoMiniAppJsSdk !!!');
  }
}
